import { defineAdminModuleManifest, lazyNamedComponent } from '@/app/modules/manifest';
import { Permission } from '@/features/auth/permissions';

export const manifest = defineAdminModuleManifest({
  moduleKey: 'orders',
  displayName: 'Đơn hàng',
  version: '1.0.0',
  permissions: [
    { code: Permission.OrdersView, name: 'Xem đơn hàng', group: 'Đơn hàng' },
    { code: Permission.OrdersManage, name: 'Quản lý đơn hàng', group: 'Đơn hàng' },
    { code: Permission.OrdersCancel, name: 'Hủy đơn hàng', group: 'Đơn hàng' },
  ],
  pages: [
    {
      pageKey: 'orders.list',
      defaultPath: '/admin/orders',
      requiredPermission: Permission.OrdersView,
      lazyComponent: lazyNamedComponent(
        () => import('@/features/orders/pages/OrderListPage'),
        'OrderListPage',
      ),
    },
    {
      pageKey: 'orders.create',
      defaultPath: '/admin/orders/new',
      requiredPermission: Permission.OrdersManage,
      lazyComponent: lazyNamedComponent(
        () => import('@/features/orders/pages/OrderEditorPage'),
        'OrderCreatePage',
      ),
    },
    {
      pageKey: 'orders.calendar',
      defaultPath: '/admin/orders/calendar',
      requiredPermission: Permission.OrdersView,
      lazyComponent: lazyNamedComponent(
        () => import('@/features/orders/pages/OrdersCalendarPage'),
        'OrdersCalendarPage',
      ),
    },
    {
      pageKey: 'orders.detail',
      defaultPath: '/admin/orders/:id',
      requiredPermission: Permission.OrdersView,
      lazyComponent: lazyNamedComponent(
        () => import('@/features/orders/pages/OrderDetailPage'),
        'OrderDetailPage',
      ),
    },
    {
      pageKey: 'orders.edit',
      defaultPath: '/admin/orders/:id/edit',
      requiredPermission: Permission.OrdersManage,
      lazyComponent: lazyNamedComponent(
        () => import('@/features/orders/pages/OrderEditorPage'),
        'OrderEditPage',
      ),
    },
  ],
  defaultNavigation: [
    {
      key: 'orders.list',
      moduleKey: 'orders',
      pageKey: 'orders.list',
      label: 'Đơn hàng',
      defaultPath: '/admin/orders',
      iconKey: 'shopping-bag',
      permissionCode: Permission.OrdersView,
      sortOrder: 20,
      isVisible: true,
      isEnabled: true,
      isSystem: true,
    },
    {
      key: 'orders.calendar',
      moduleKey: 'orders',
      pageKey: 'orders.calendar',
      label: 'Lịch giao',
      defaultPath: '/admin/orders/calendar',
      iconKey: 'calendar-days',
      permissionCode: Permission.OrdersView,
      sortOrder: 40,
      isVisible: true,
      isEnabled: true,
      isSystem: true,
    },
    {
      key: 'orders.create',
      parentKey: 'orders.list',
      moduleKey: 'orders',
      pageKey: 'orders.create',
      label: 'Tạo đơn hàng',
      defaultPath: '/admin/orders/new',
      permissionCode: Permission.OrdersManage,
      sortOrder: 10,
      isVisible: false,
      isEnabled: true,
      isSystem: true,
    },
    {
      key: 'orders.detail',
      parentKey: 'orders.list',
      moduleKey: 'orders',
      pageKey: 'orders.detail',
      label: 'Chi tiết đơn hàng',
      defaultPath: '/admin/orders/:id',
      permissionCode: Permission.OrdersView,
      sortOrder: 20,
      isVisible: false,
      isEnabled: true,
      isSystem: true,
    },
    {
      key: 'orders.edit',
      parentKey: 'orders.list',
      moduleKey: 'orders',
      pageKey: 'orders.edit',
      label: 'Chỉnh sửa đơn hàng',
      defaultPath: '/admin/orders/:id/edit',
      permissionCode: Permission.OrdersManage,
      sortOrder: 30,
      isVisible: false,
      isEnabled: true,
      isSystem: true,
    },
  ],
});
